#cloud-config

#package_update: true
#package_upgrade: true
#package_reboot_if_required: true

packages:
  - iptables-persistent
  - strongswan
  - curl
  - collectd
  - conntrack
  - net-tools
  - iperf3
  - ifupdown
  - wget

write_files:
  - path: /etc/ipsec.d/vpn.conf
    content: |
      conn Tunnel1
              auto=start
              left=%defaultroute
              leftid=${do_vpn_ip}
              right=${remote_vpn_ip}
              type=tunnel
              leftauth=psk
              rightauth=psk
              keyexchange=ikev1
              ike=aes128-sha1-modp1024
              ikelifetime=8h
              esp=aes128-sha1-modp1024
              lifetime=1h
              keyingtries=%forever
              leftsubnet=0.0.0.0/0
              rightsubnet=0.0.0.0/0
              dpddelay=10s
              dpdtimeout=30s
              dpdaction=restart
              mark=100

  - path: /etc/ipsec.secrets
    content: |
      ${do_vpn_ip} ${remote_vpn_ip} : PSK "${vpn_psk}"

  - path: /usr/local/bin/add-netplan-route.sh
    permissions: '0755'
    content: |
${add_netplan_script}

  - path: /root/setup-vpn.sh
    permissions: '0755'
    content: |
${setup_vpn_script}

runcmd:
  - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq && chmod +x /usr/local/bin/yq
  - /root/setup-vpn.sh ${do_vpn_ip} ${remote_vpn_ip}
